python3  cameraCalibration.py intrinsic/160.yaml extrinsic/160.yaml 160 voxel > images_data/cameras.txt
python3  cameraCalibration.py intrinsic/161.yaml extrinsic/161.yaml 161 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/162.yaml extrinsic/162.yaml 162 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/163.yaml extrinsic/163.yaml 163 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/164.yaml extrinsic/164.yaml 164 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/165.yaml extrinsic/165.yaml 165 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/166.yaml extrinsic/166.yaml 166 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/167.yaml extrinsic/167.yaml 167 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/168.yaml extrinsic/168.yaml 168 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/169.yaml extrinsic/169.yaml 169 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/170.yaml extrinsic/170.yaml 170 voxel >> images_data/cameras.txt
python3  cameraCalibration.py intrinsic/170.yaml extrinsic/171.yaml 171 voxel >> images_data/cameras.txt